version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: database_discussions
    ports:
      - "3306:3306"
    volumes:
      - ./database_management/mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Chemin vers le Dockerfile de votre application
    volumes:
      - ./data/raw/data_acquisition:/app/data/raw  # Chemin vers vos fichiers CSV
    depends_on:
      - mysql
